apiVersion: v1
kind: Service
metadata:
  name: hellows-app
  namespace: hellows
  labels:
    app: hellows-app
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8080
  selector:
    app: hellows-app

